config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  
  resources :registrations, only: [:new, :create, :edit, :update]

  resources :confirmations, only: [:new, :create]
  get 'user/confirm', to: 'confirmations#confirm'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :passwords, only: [:new, :create]
  get 'password/reset', to: 'passwords#edit'
  patch 'password/reset', to: 'passwords#update'

  get 'admin', to: redirect('admin/deals')

  namespace :admin do
    resources :deals
    resources :users, except: [:destroy]
    resources :orders, only: [:index, :show], param: :invoice_number do
      member do
        patch 'cancel'
        patch 'deliver'
      end
    end

    namespace :report do
      resources :deals_report, only: [:index]
      resources :customers_report, only: [:index]
      resources :revenue_report, only: [:index]
    end
  end

  resources :deals, only: [:index, :show] do
    member do
      get 'polling'
    end
  end

  resources :line_items, only: [:create, :destroy, :update]

  resources :orders, only: [:index, :destroy, :show], param: :invoice_number do
    patch 'cancel', on: :member
  end
  get 'cart', to: 'orders#cart'

  resources :addresses, only: [:new, :create]
  patch 'address/associate_address', to: "addresses#associate_address"

  resources :payments, only: [:new, :create]

  namespace :api do
    namespace :v1 do
      resources :deals, only: [] do
        collection do
          get 'live'
          get 'expired'
        end
      end

      resources :orders, path: :myorders, only: [:index]
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include TokenGenerator
  include Checkout
  include Presentable

  VALID_STATES = %w(cart address payment completed cancelled delivered)

  ## ASSOCIATIONS
  belongs_to :user
  has_many :line_items, dependent: :destroy
  has_many :deals, through: :line_items
  belongs_to :address, optional: true
  has_many :payments, dependent: :destroy

  ## VALIDATIONS
  validates :invoice_number, presence: true,  uniqueness: { allow_blank: true }
  validates :loyalty_discount, allow_blank: true, numericality: { greater_than_or_equal_to: ENV['minimum_loyalty_discount'].to_i }
  validates :total_amount, allow_blank: true, numericality: { greater_than_or_equal_to: ENV['minimum_order_total_amount'].to_i }
  validates :state, inclusion: { in: VALID_STATES}

  ## SCOPES
  scope :incomplete, ->{ where(completed_at: nil) }
  scope :complete, ->{ where.not(completed_at: nil) }
  scope :ready_for_delivery, ->{ where(state: 'completed') }
  scope :cancelled, ->{ where(state: 'cancelled') }
  scope :delivered, ->{ where(state: 'delivered') }
  scope :search_by_email, ->(email) { joins(:user).where("email LIKE ?", "%#{email}%") }

  ## CALLBACKS
  before_destroy :ensure_order_incomplete
  before_validation :generate_invoice_number, on: :create


  def pretty_errors
    errors.full_messages.join("<br>")
  end

  def add_deal(deal, line_item_quantity = 1)
    line_item_temp = line_items.find_by(deal_id: deal.id)
    if line_item_temp.present?
      line_item_temp.quantity += line_item_quantity
      line_item_temp.save
    else
      line_item_temp = line_items.create(deal_id: deal.id, price: deal.price, discount_price: deal.discount_price, quantity: line_item_quantity)
    end
    line_item_temp
  end

  def associate_address(address)
    update(address: address)
  end

  def total_items_quantity
    line_items.sum(:quantity)
  end

  def items_subtotal
    line_items.sum(:discount_price)
  end

  def total_amount_in_cents
    total_amount * 100
  end

  def to_param
    invoice_number
  end

  private

    def ensure_order_incomplete
      if completed_at.present?
        errors[:base] << I18n.t(:order_cannot_be_deleted, scope: [:flash, :alert])
        throw :abort
      end    
    end

    def generate_invoice_number
      self.invoice_number = generate_unique_token(:invoice_number, 8, 'INV-')
    end

end 

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  before_action :fetch_orders, only: :index
  before_action :get_order, only: [:show, :cancel, :deliver]

  def index
    @ready_for_delivery_orders = @orders.ready_for_delivery.order(completed_at: :desc)
    @delivered_orders = @orders.delivered.order(delivered_at: :desc)
    @cancelled_orders = @orders.cancelled.order(cancelled_at: :desc)
  end

  def show
    
  end

  def cancel
    begin
      @order.cancelled_by!(current_user)
      flash[:notice] = I18n.t(:order_successfully_cancelled, scope: [:flash, :notice])
    rescue => e
      flash[:alert] = e.message
    end
    redirect_to admin_order_path(@order)
  end

  def deliver
    if @order.deliver
      flash[:notice] = I18n.t(:order_successfully_marked_delivered, scope: [:flash, :notice])
    else
      flash[:alert] = @order.pretty_errors
    end
    redirect_to admin_order_path(@order)
  end


  private

    def get_order
      @order = Order.find_by(invoice_number: params[:invoice_number])
      if @order.nil?
        render_404
      end
    end

    def fetch_orders
      if params[:search].present? && params[:search][:email].present?
        @orders = Order.search_by_email(params[:search][:email])
      else
        @orders = Order.all
      end 
    end

end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < Api::V1::BaseController
  
  before_action :get_user

  def index
    @orders = @user.orders.includes(:address, :line_items, :payments)

    render json: @orders
  end

  private

    def get_user
      @user = User.find_by(api_token: params[:token])

      if @user.nil?
        render json: { error: I18n.t(:not_authorized, scope: :api)}, status: 401 and return
      end

    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :get_order, only: [:destroy, :show, :cancel]

  def cart
  end

  def destroy
    if @order.destroy
      redirect_to root_path, notice: I18n.t(:cart_emptied, scope: [:flash, :notice])
    else
      redirect_to cart_path, alert: @order.pretty_errors
    end
  end

  def show
  end

  def index
    @ready_for_delivery_orders = current_user.orders.ready_for_delivery.order(completed_at: :desc)
    @delivered_orders = current_user.orders.delivered.order(delivered_at: :desc)
    @cancelled_orders = current_user.orders.cancelled.order(cancelled_at: :desc)
  end

  def cancel
    begin
      @order.cancelled_by!(current_user)
      flash[:notice] = I18n.t(:order_successfully_cancelled, scope: [:flash, :notice])
    rescue => e
      flash[:alert] = e.message
    end
    redirect_to order_path(@order)
  end
  

  private

    def get_order
      @order = current_user.orders.find_by(invoice_number: params[:invoice_number])
      unless @order.present?
        render_404
      end
    end

end

app/views/admin/orders/_orders.html.erb
<br>
<div class="table-responsive">
    <div class="panel panel-default">  
      <table class="table table-striped table-hover">
        
        <thead>
          <tr>
            <th nowrap>#</th>
            <th nowrap>INVOICE NUMBER</th>
            <th nowrap>USER EMAIL</th>
            <th nowrap>COMPLETED AT</th>
            <th nowrap>DELIVERED AT</th>
            <th nowrap>CANCELLED AT</th>
            <th nowrap>LOYALTY DISCOUNT</th>
            <th nowrap>GRAND SUBTOTAL</th>
            <th nowrap></th>
          </tr>
        </thead>
        
        <tbody>
          <% orders.includes(:user).each.with_index(1) do |order, serial_number| %>
            <tr>
              <td><%= serial_number %></td>

              <td><%= order.invoice_number %></td>

              <td><%= order.user.email %></td>
            
              <td><%= order.completed_at %></td>
                
              <td><%= order.presenter.delivery_time %></td>

              <td><%= order.presenter.cancellation_time %></td>

              <td><%= number_to_currency(order.loyalty_discount) %></td>

              <td><%= number_to_currency(order.total_amount) %></td>

              <td>
                <%= link_to t(:page_action_show, scope: [:action]), admin_order_path(order.invoice_number) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/admin/orders/index.html.erb
<% content_for :page_title do %>
  <span class="col-md-offset-5 col-xs-offset-5 page-title"><%= t(:order_page_title, scope: [:action]) %></span>
<% end %>

<div class="browse-order clearfix">
  <%= form_with(scope: :search, url: admin_orders_path, local: true, method: :get, class: 'navbar-form navbar-left') do |form| %>
    <%= form.text_field :email, class: 'form-control', placeholder: 'test@mail.com' %>
    <%= form.submit I18n.t(:filter, scope: [:action]), class: 'btn btn-default' %>
  <% end %>
</div>
<br>

<div class="col-md-12 col-xs-12">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#ready-for-delivery-orders" data-toggle="tab" aria-expanded="true">Ready for Delivery Orders</a></li>
    <li class=""><a href="#delivered-orders" data-toggle="tab" aria-expanded="false">Delivered Orders</a></li>
    <li class=""><a href="#cancelled-orders" data-toggle="tab" aria-expanded="false">Cancelled Orders</a></li>
  </ul>

  <div id="myTabContent" class="tab-content">
    <div class="tab-pane fade active in" id="ready-for-delivery-orders">
      <% if @ready_for_delivery_orders.empty? %>
        <h3>No Orders for delivery</h3>
      <% else %>
        <%= render partial: 'orders', object: @ready_for_delivery_orders %>
      <% end %>
    </div>

    <div class="tab-pane fade" id="delivered-orders">
      <% if @delivered_orders.empty? %>
        <h3>No Delivered Orders</h3>
      <% else %>
        <%= render partial: 'orders', object: @delivered_orders %>
      <% end %>
    </div>
    
    <div class="tab-pane fade" id="cancelled-orders">
      <% if @cancelled_orders.empty? %>
        <h3>No Cancelled Orders</h3>
      <% else %>
        <%= render partial: 'orders', object: @cancelled_orders %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<% content_for :page_title do %>
  <span class="page-title <%= @order.completed?? 'col-md-offset-5 col-xs-offset-5' : 'col-md-offset-4 col-xs-offset-4' %>">
    <%= link_to t(:order_page_title, scope: :action), admin_orders_url %> / 
    <%= @order.invoice_number %>
  </span>
<% end %>

<% if @order.completed? %>
  <% content_for :page_action do %>
    <%= link_to t(:page_action_cancel, scope: :action), cancel_admin_order_path(@order), method: :patch, data: { confirm: 'Are you sure you want to cancel this order?' }, class: 'btn btn-danger page-action col-md-offset-7 col-xs-offset-7' %>
    <%= link_to t(:page_action_deliver, scope: :action), deliver_admin_order_path(@order), method: :patch, data: { confirm: 'Are you sure you want to mark this order delivered?' }, class: 'btn btn-success page-action col-md-offset- col-xs-offset-' %>
  <% end %>
<% end %>

<div class="col-md-10 col-xs-offset-1 col-md-offset-1 col-xs-10">
  <div class="panel panel-default">
    <div class="panel-body">
      <section class="table-responsive">
        <table class="table table-hover table-condensed">
          <thead>
            <th nowrap></th>
            <th nowrap>TITLE</th>
            <th nowrap>UNIT PRICE</th>
            <th nowrap>QUANTITY</th>
            <th nowrap>LOYALTY DISCOUNT</th>
            <th nowrap>TOTAL PRICE</th>
            <th nowrap></th>

          </thead>
          <tbody>
            <% @order.line_items.includes(deal: :images).each do |line_item| %>
              <tr>
                <td><%= link_to image_tag(line_item.deal.images.first.avatar.url(:mini)), admin_deal_path(line_item.deal) %></td>
                <td><%= link_to line_item.deal.title, admin_deal_path(line_item.deal) %></td>
                <td>
                  <p>
                    <span class="text-muted"><del><%= number_to_currency(line_item.price) %></del></span>
                    <span class="lead text-success"><%= number_to_currency(line_item.discount_price) %></span>
                  </p>
                </td>
                <td><%= line_item.quantity %></td>
                <td><%= number_to_currency(line_item.loyalty_discount) %></td>
                <td><%= number_to_currency(line_item.total_amount) %></td>
                <td>
                  <%= link_to I18n.t(:view_deal, scope: :action), admin_deal_path(line_item.deal) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </section>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8 col-xs-8 col-md-offset-2">
    <div class="panel panel-default">  
      
      <table class='table table-striped table-hover'>
        <tr>
          <td>Invoice Number</td>
          <td><%= @order.invoice_number %></td>
        </tr>
        
        <tr>
          <td>State</td>
          <td><%= @order.state.capitalize %></td>
        </tr>

        <tr>
          <td>User Email</td>
          <td><%= @order.user.email %></td>
        </tr>

        <tr>
          <td>Completed On</td>
          <td><%= @order.completed_at %></td>
        </tr>
        
        <tr>
          <td>Delivered On</td>
          <td><%= @order.presenter.delivery_time %></td>
        </tr>
        
        <tr>
          <td>Cancelled On</td>
          <td><%= @order.presenter.cancellation_time %></td>
        </tr>

        <tr>
          <td>Items's Quantity</td>
          <td><%= @order.total_items_quantity %></td>
        </tr>

        <tr>
          <td>Item(s) Subtotal</td>
          <td><%= number_to_currency(@order.items_subtotal) %></td>
        </tr>

        <tr>
          <td>Loyalty Discount</td>
          <td><%= number_to_currency(@order.loyalty_discount) %></td>
        </tr>

        <tr>
          <td>Grand Subtotal</td>
          <td><%= number_to_currency(@order.total_amount) %></td>
        </tr>
      </table>
    </div>
  </div>
</div>