config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  
  resources :registrations, only: [:new, :create, :edit, :update]

  resources :confirmations, only: [:new, :create]
  get 'user/confirm', to: 'confirmations#confirm'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :passwords, only: [:new, :create]
  get 'password/reset', to: 'passwords#edit'
  patch 'password/reset', to: 'passwords#update'

  get 'admin', to: redirect('admin/deals')

  namespace :admin do
    resources :deals
    resources :users, except: [:destroy]
    resources :orders, only: [:index, :show], param: :invoice_number do
      member do
        patch 'cancel'
        patch 'deliver'
      end
    end

    namespace :report do
      resources :deals_report, only: [:index]
      resources :customers_report, only: [:index]
      resources :revenue_report, only: [:index]
    end
  end

  resources :deals, only: [:index, :show] do
    member do
      get 'polling'
    end
  end

  resources :line_items, only: [:create, :destroy, :update]

  resources :orders, only: [:index, :destroy, :show], param: :invoice_number do
    patch 'cancel', on: :member
  end
  get 'cart', to: 'orders#cart'

  resources :addresses, only: [:new, :create]
  patch 'address/associate_address', to: "addresses#associate_address"

  resources :payments, only: [:new, :create]

  namespace :api do
    namespace :v1 do
      resources :deals, only: [] do
        collection do
          get 'live'
          get 'expired'
        end
      end

      resources :orders, path: :myorders, only: [:index]
    end
  end
end

app/views/shared/_admin_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FLASH SALE', admin_url, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to t(:deals, scope: [:action]), admin_deals_path %></li>
        <li><%= link_to t(:users, scope: [:action]), admin_users_path %></li>
        <li><%= link_to t(:orders, scope: [:action]), admin_orders_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Reports<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to t(:customers_report), admin_report_customers_report_index_path %></li>
            <li><%= link_to t(:revenue_report), admin_report_revenue_report_index_path %></li>
            <li><%= link_to t(:deals_report), admin_report_deals_report_index_path %></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <%= image_tag 'user_profile_logo.png', size: '25x25' %>
          <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to t(:update_profile, scope: [:action]), edit_registration_url(current_user), method: :get %></li>
            <li class="divider"></li>
            <li><%= link_to 'Logout', logout_url, method: :delete %></li>
          </ul>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/views/shared/_content_header.html.erb
<% if content_for?(:page_title) || content_for?(:page_action) %>
  
  <div class = 'row content-header'>
    <% if content_for?(:page_title) %>
      <p class="<%= content_for?(:page_action)? 'col-md-6 col-xs-6' : 'col-md-12 col-xs-12' %> " >
        <%= yield :page_title %>
      </p>
    <% end %>

    <% if content_for?(:page_action) %>
      <p class="<%= content_for?(:page_title)? 'col-md-6 col-xs-6' : 'col-md-12 col-xs-12' %>" >
        <%= yield :page_action %>
      </p>
    <% end %>

  </div>
<% end %>

app/views/shared/_final_cart.html.erb
<div class="col-md-10 col-md-offset-1 col-xs-10 col-xs-offset-1">
    
    <div class="table-responsive ">
      <div class="panel panel-default">
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th></th>
              <th nowrap>TITLE</th>
              <th nowrap>UNIT PRICE</th>
              <th nowrap>QUANTITY</th>
              <th nowrap>LOYALTY DISCOUNT</th>
              <th nowrap>TOTAL PRICE</th>
            </tr>
          </thead>
          <tbody>
            <% current_order.line_items.includes(:deal).each do |line_item| %>
              <tr>
                <td><%= link_to image_tag(line_item.deal.images.first.avatar.url(:mini)), deal_url(line_item.deal) %></td>
                <td><%= link_to line_item.deal.title, deal_url(line_item.deal) %></td>
                <td>
                  <p>
                    <span class="text-muted"><del><%= number_to_currency(line_item.price) %></del></span>
                    <span class="lead text-success"><%= number_to_currency(line_item.discount_price) %></span>
                  </p>
                </td>
                <td><%= line_item.quantity %></td>
                <td><%= number_to_currency(line_item.loyalty_discount) %></td>
                <td><%= number_to_currency(line_item.total_amount) %></td>
              </tr>
            <% end %>

            <tr>
              <td colspan="4"><strong><p class="col-md-offset-6">Total Loyalty Discount</p></strong></td>
              <td colspan="2"><strong><%= number_to_currency(current_order.loyalty_discount) %></strong></td>
            <tr>
              <td colspan="5"><strong><p class="col-md-offset-8">SUBTOTAL:</p></strong></td>
              <td colspan="2"><strong><%= number_to_currency(current_order.total_amount) %></strong></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

  </div>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
  <div class="alert alert-dismissible <%= if flash.notice.nil?
        'alert-danger'
      else
        'alert-success'
      end %>", data-hide='auto'>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <% flash.each do |name, msg| %>
      <%= content_tag :p, msg.html_safe, class: 'mb-0' %>
    <% end %>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if model_object.errors.any? %>
  <div class="alert alert-dismissible alert-danger text-center form-errors">
    
    <strong><p><%= "#{model_object.class} couldn't be saved due to " + pluralize(model_object.errors.count, 'error') %></p></strong>

      <% model_object.errors.full_messages.each do |message| %>
        <p><%= message.capitalize %></p>
      <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FLASH SALE', root_url, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to t(:deals, scope: [:action]), deals_url %></li>
        </ul>

        <%= form_with(scope: :search, url: deals_path, local: true, method: :get, class: 'navbar-form navbar-left') do |form| %>
          <%= form.text_field :deal_text, class: 'form-control', placeholder: 'clothes' %>
          <%= form.submit I18n.t(:browse_deals, scope: [:action]), class: 'btn btn-default' %>
        <% end %>

      <% if current_user.present? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to image_tag('cart_logo.png', size: '25x25'), cart_url %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= image_tag 'user_profile_logo.png', size: '25x25' %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to t(:myorders, scope: :action), orders_path %></li>
              <li><%= link_to t(:update_profile, scope: [:action]), edit_registration_url(current_user), method: :get %></li>
              <li class="divider"></li>
              <li><%= link_to 'Logout', logout_url, method: :delete %></li>
            </ul>
          </li>
        </ul>

      <% else %>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t(:login, scope: [:action]).upcase, login_url %></li>
        </ul>

      <% end %>
    </div>
  </div>
</nav>