config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  
  resources :registrations, only: [:new, :create, :edit, :update]

  resources :confirmations, only: [:new, :create]
  get 'user/confirm', to: 'confirmations#confirm'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :passwords, only: [:new, :create]
  get 'password/reset', to: 'passwords#edit'
  patch 'password/reset', to: 'passwords#update'

  get 'admin', to: redirect('admin/deals')

  namespace :admin do
    resources :deals
    resources :users, except: [:destroy]
    resources :orders, only: [:index, :show], param: :invoice_number do
      member do
        patch 'cancel'
        patch 'deliver'
      end
    end

    namespace :report do
      resources :deals_report, only: [:index]
      resources :customers_report, only: [:index]
      resources :revenue_report, only: [:index]
    end
  end

  resources :deals, only: [:index, :show] do
    member do
      get 'polling'
    end
  end

  resources :line_items, only: [:create, :destroy, :update]

  resources :orders, only: [:index, :destroy, :show], param: :invoice_number do
    patch 'cancel', on: :member
  end
  get 'cart', to: 'orders#cart'

  resources :addresses, only: [:new, :create]
  patch 'address/associate_address', to: "addresses#associate_address"

  resources :payments, only: [:new, :create]

  namespace :api do
    namespace :v1 do
      resources :deals, only: [] do
        collection do
          get 'live'
          get 'expired'
        end
      end

      resources :orders, path: :myorders, only: [:index]
    end
  end
end

app/models/deal.rb
class Deal < ApplicationRecord

  include Presentable

  ## ASSOCIATIONS
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: proc { |attributes| attributes[:avatar].blank? }

  has_many :line_items, dependent: :restrict_with_error

  ## VALIDATIONS
  with_options presence: true do
    validates :title, :description, :price, :discount_price, :quantity
  end

  with_options allow_blank: true do
    validates :title, uniqueness: { case_sensitive: false }
    
    validates :price, numericality: { greater_than_or_equal_to: ENV['minimum_price'].to_f }
    validates :discount_price, numericality: { greater_than_or_equal_to: ENV['minimum_discount_price'].to_f }
    
    validates :quantity, numericality: { 
      only_integer: true,
      greater_than_or_equal_to: 0 }
  end

  validates_with DiscountPriceValidator

  validate :publishing_date_must_be_after_today, if: :publishing_date_changed?
  
  validate :associated_images_count, if: :has_publishing_date?

  validate :quantity_count, if: :has_publishing_date?

  validate :publishing_date_cannot_be_updated, on: :update, if: [:publishing_date_changed?, :publishing_date_was]
  
  validate :maximum_number_of_deals_per_publishing_date, if: :has_publishing_date?

  ## CALLBACKS
  # when image is destroyed images.size changes only after update
  # so this callback verifies if image_count_valid
  after_update :ensure_images_count_valid, if: :has_publishing_date?
  before_destroy :ensure_deal_not_live_or_expired

  ## SCOPE
  scope :publishable_on, ->(date = Date.current) { where(publishing_date: date) }
  scope :live, ->{ where("start_at <= ? AND end_at >= ?", Time.current, Time.current) }
  scope :expired, ->{ where("end_at < ?", Time.current) }
  scope :future, -> { where(start_at: nil).where("publishing_date >= ?", Date.current) }
  scope :unpublished, ->{ where(publishing_date: nil) }
  scope :chronologically_by_end_at, ->{ order(:end_at) }
  scope :reverse_chronologically_by_end_at, ->{ order(end_at: :desc) }
  scope :search_by_title_and_description, ->(title, description) { where("title LIKE ? OR description LIKE ?", "%#{title}%", "%#{description}%") }

  def has_publishing_date?
    publishing_date.present?
  end

  def publishability_errors
    issues = []
      
    if has_invalid_associated_images_count?
      issues << 'Image ' + I18n.t(:image_greater_than, scope: [:errors, :custom_validation], image_count: ENV['published_deal_minimum_image_count'].to_i) 
    end

    if has_invalid_quantity_count?
      issues << 'Quantity ' + I18n.t(:quantity_greater_than, scope: [:errors, :custom_validation], quantity_count: ENV['published_deal_minimum_quantity_count'].to_i)
    end

    issues
  end

  def is_live?
    start_at.present? && end_at.present? && Time.current.between?(start_at, end_at)
  end

  def is_expired?
    start_at.present? && end_at.present? && end_at < Time.current
  end

  def sellable?
    is_live? && quantity > 0
  end

  def pretty_errors
    errors.full_messages.join("<br>")
  end

  def self.order_by(option)
    case option
    when 'price_ascending'
      @deals = order(:price)
    when 'price_descending'
      @deals = order(price: :desc)
    when 'discount_price_ascending', 'loyalty_discount_ascending'
      @deals = order(:discount_price)
    when 'discount_price_descending', 'loyalty_discount_descending'
      @deals = order(discount_price: :desc)
    else
      @deal = all
    end
  end

  def selling_price_with_maximum_loyalty_discount
    (discount_price * (100 - LOYALTY_DISCOUNT_SLABS['maximum'])) / 100
  end

  private

    def publishing_date_must_be_after_today
      if has_publishing_date? && publishing_date <= Date.current
        errors[:publishing_date] << I18n.t(:publishing_date_must_be_after_today, scope: [:errors, :custom_validation], date: Date.current)
      end
    end

    def has_invalid_associated_images_count?
      images.size < ENV['published_deal_minimum_image_count'].to_i
    end

    def associated_images_count
      if has_invalid_associated_images_count?
        errors[:images] << I18n.t(:image_greater_than, scope: [:errors, :custom_validation], image_count: ENV['published_deal_minimum_image_count'].to_i) 
      end
    end

    def has_invalid_quantity_count?
      quantity? && quantity < ENV['published_deal_minimum_quantity_count'].to_i
    end

    def quantity_count
      if has_invalid_quantity_count?
        errors[:quantity] << I18n.t(:quantity_greater_than, scope: [:errors, :custom_validation], quantity_count: ENV['published_deal_minimum_quantity_count'].to_i)
      end
    end

    def publishing_date_cannot_be_updated
      # publishing date cannot be changed when deal is live
      if is_live? 
        errors[:publishing_date] << I18n.t(:publishing_date_cannot_be_changed_for_live_deal, scope: [:errors, :custom_validation])
    
      # publishing date cannot be changed after deal has expired
      elsif is_expired?
        errors[:publishing_date] << I18n.t(:publishing_date_cannot_be_changed_after_deal_expire, scope: [:errors, :custom_validation])
     
      # publishing date cannot be changed 24.hours before deal goes live
      elsif publishing_date_was.to_time - Time.current < HOURS_BEFORE_START_WHEN_PUBLISHING_DATE_CANNOT_BE_CHANGED
        errors[:publishing_date] << I18n.t(:publishing_date_cannot_be_changed_h_hours_before_deal_goes_live, scope: [:errors, :custom_validation], h: ENV['bumber_of_hours_before_start_when_publishing_date_cannot_be_changed'])
      end
    end

    def maximum_number_of_deals_per_publishing_date
      if self.class.publishable_on(publishing_date).count >= ENV['maximum_number_of_deal_per_publishing_date'].to_i
        errors[:publishing_date] << I18n.t(:cannot_have_more_deals, scope: [:errors, :custom_validation], maximum_number_of_deals: ENV['maximum_number_of_deal_per_publishing_date'].to_i)
      end
    end

    def ensure_images_count_valid
      if has_invalid_associated_images_count?
        errors[:images] << I18n.t(:image_greater_than, scope: [:errors, :custom_validation], image_count: ENV['published_deal_minimum_image_count'].to_i) 
        raise ActiveRecord::Rollback
      end

    end

    def ensure_deal_not_live_or_expired
      if is_expired? || is_live?
        errors[:base] << I18n.t(:live_or_expired_deal_cannot_be_deleted, scope: [:deal, :errors])
        throw :abort
      end
    end
end

app/controllers/admin/deals_controller.rb
class Admin::DealsController < Admin::BaseController
  
  before_action :set_deal, only: [:edit, :update, :show, :destroy]

  def index
    @live_deals = Deal.live.includes(:images).chronologically_by_end_at
    @expired_deals = Deal.expired.includes(:images).reverse_chronologically_by_end_at
    @future_deals = Deal.future.includes(:images)
    @unpublished_deals = Deal.unpublished.includes(:images)
  end

  def new
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(new_deal_params)
    if @deal.save
      redirect_to admin_deals_url, notice: t(:deal_created, scope: [:flash, :notice])
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @deal.update(update_deal_params)
      redirect_to admin_deals_url, notice: t(:deal_updated, scope: [:flash, :notice])
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    if @deal.destroy
      redirect_to admin_deals_path, notice: t(:deal_successfully_destroyed, scope: [:flash, :notice])
    else
      redirect_to admin_deals_path, alert: @deal.pretty_errors
    end
  end

  private

    def new_deal_params
      params.require(:deal).permit(:title, :description, :price, :discount_price, :quantity, :publishing_date, images_attributes: [:avatar, :_destroy])
    end

    def update_deal_params
      params.require(:deal).permit(:title, :description, :price, :discount_price, :quantity, :publishing_date, images_attributes: [:id, :avatar, :_destroy])
    end

    def set_deal
      @deal = Deal.find_by(id: params[:id])
      unless @deal.present?
        render_404
      end
    end
end

app/controllers/api/v1/deals_controller.rb
class Api::V1::DealsController < Api::V1::BaseController

  def live
    @live_deals = Deal.live.chronologically_by_end_at
    
    render json: @live_deals
  end

  def expired
    @expired_deals = Deal.expired.reverse_chronologically_by_end_at
    
    render json: @expired_deals
  end

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  before_action :get_deals, only: :index
  before_action :set_deal, only: [:show]
  skip_before_action :authenticate_user, only: [:index]

  def index
    @live_deals = @deals.live.includes(:images).chronologically_by_end_at
    @expired_deals = @deals.expired.includes(:images).reverse_chronologically_by_end_at
  end

  def show
  end

  private

    def set_deal
      @deal = Deal.find_by(id: params[:id])
      unless @deal.present?
        render_404
      end
    end

    def get_deals
      if params[:search].present? && params[:search][:deal_text].present?
        @deals = Deal.search_by_title_and_description(params[:search][:deal_text], params[:search][:deal_text])
      else
        @deals = Deal.all
      end
    end

end

app/views/deals/_expired_deals.html.erb
<%= javascript_include_tag "slideshow.js" %>

<article class="expired-deals col-md-12 col-xs-12">
  <h2 class="col-md-6 col-md-offset-5 col-xs-6 col-xs-offset-5">Past Deals</h2>

    <% expired_deals.each do |deal| %>
      <section class="deal panel panel-default col-md-4 col-xs-6">
        <div class="panel-body">

          <div class="deal-images col-md-11 col-xs-11">
            <ul class= 'bxslider',  data-slider='images-slider', data-width='240'>
              <% if deal.images.exists? %>
              
                  <% deal.images.each do |deal_image| %>
                    <li><%= image_tag deal_image.avatar.url(:medium) %></li>
                  <% end %>
              
              <% else %>
                <li><%= image_tag NO_IMAGE_AVAILABLE_PATH, size: '240' %></li>
              <% end %>
            </ul>
          </div>

          <h3 class="text-centre"><strong><%= deal.title %></strong></h3>
 
          <div class="row">
            <div class="col-md-6 col-xs-6">
              <p>
                <span class="text-muted"><del><%= number_to_currency(deal.price) %><del></span>
                <span class="lead text-success"><%= number_to_currency(deal.discount_price) %></span>
              </p>
            </div>
            <div class="col-md-4 col-md-offset-1 col-xs-5 col-xs-offset-1">
              <p class="lead text-danger">Sold Out</p>
              <%= link_to I18n.t(:view_deal, scope: :action), deal_url(deal), class: 'btn btn-primary' %>
            </div>
          </div>

          <hr class="col-md-11">
          <div class="col-md-12 col-xs-12">
            <%= strip_html_and_truncate(deal.description, 80) %>
          </div>

        </div>
      </section>
    <% end %>

</article>

app/views/deals/_live_deals.html.erb
<%= javascript_include_tag "slideshow.js" %>

<article class="live-deals col-md-12 col-xs-12">
  <h2 class="col-md-6 col-md-offset-5 col-xs-6 col-xs-offset-5">Live Deals</h2>

    <% live_deals.each do |deal| %>
      <section class="deal panel panel-default col-md-4 col-xs-6">
        <div class="panel-body">

          <div class="deal-countdown-timer text-centre", data-timer='yes', data-end-at="<%= deal.end_at %>"></div>

          <div class="deal-images col-md-11 col-xs-11">
            <ul class= 'bxslider',  data-slider='images-slider', data-width='240'>
              <% if deal.images.exists? %>
              
                  <% deal.images.each do |deal_image| %>
                    <li><%= image_tag deal_image.avatar.url(:medium) %></li>
                  <% end %>
              
              <% else %>
                <li><%= image_tag NO_IMAGE_AVAILABLE_PATH, size: '240' %></li>
              <% end %>
            </ul>
          </div>

          <h3 class="text-centre"><strong><%= deal.title %></strong></h3>
          <div class="row">
            <div class="col-md-6 col-xs-6">
              <p>
                <span class="text-muted"><del><%= number_to_currency(deal.price) %><del></span>
                <span class="lead text-success"><%= number_to_currency(deal.discount_price) %></span>
              </p>
              <p>Only <span class="lead text-primary"><%= deal.quantity %></span> more left</p>
            </div>

            <div class="col-md-4 col-md-offset-1 col-xs-5 col-xs-offset-1">
              <%= link_to I18n.t(:view_deal, scope: :action), deal_url(deal), class: 'btn btn-primary btn-lg view-deal-btn' %>
            </div>
          </div>

          <hr class="col-md-11">
          <div class="col-md-12 col-xs-12">
            <%= strip_html_and_truncate(deal.description, 80) %>
          </div>

        </div>
      </section>
    <% end %>

</article>

app/views/deals/index.html.erb
<% if @live_deals.empty? %>
  <h2 class="col-md-6 col-md-offset-4 col-xs-6 col-xs-offset-4">There are no Live Deals available.</h2>
<% else %>
  <%= render 'live_deals', live_deals: @live_deals %>
<% end %>

<hr class="col-md-12">
<% if @expired_deals.empty? %>
  <h2 class="col-md-6 col-md-offset-4 col-xs-6 col-xs-offset-4">There are no Past Deals available.</h2>
<% else %>
  <%= render 'expired_deals', expired_deals: @expired_deals %>
<% end %>

app/views/deals/show.html.erb
<%= javascript_include_tag "slideshow.js" %>
<%= javascript_include_tag "deal_poller.js" %>


<article class="deal-view panel panel-default">
  <div class= 'panel-body'>

    <h1 class="deal-title col-md-12"><%= @deal.title %></h1>

    <section class="col-md-7 left-side">
      <div class="deal-images col-md-12 col-xs-12 ">
        <ul class= 'bxslider deal-show-images', data-slider='images-slider', data-width='600'> 
          <% if @deal.images.exists? %>
          
              <% @deal.images.each do |deal_image| %>
                <li><%= image_tag deal_image.avatar.url(:large) %></li>
              <% end %>
          
          <% else %>
            <li><%= image_tag NO_IMAGE_AVAILABLE_PATH, size: '600' %></li>
          <% end %>
        </ul>
      </div>
    </section>
  
    <section class="col-md-5 deal-details right-side">
      <div class="col-md-10 col-xs-10 col-md-offset-1">
        <% if @deal.sellable? %>
          <p class="deal-countdown-timer text-centre", data-timer='yes', data-end-at="<%= @deal.end_at %>", data-poll-link= "<%= polling_deal_url(@deal) %>" , data-poll-interval= "<%= ENV['polling_interval'].to_i %>" ></p>
        <% end %>
        <h2>
          <span class="lead text-danger text-muted "><del><%= number_to_currency(@deal.price) %><del></span>
          <span class="text-success"><%= number_to_currency(@deal.discount_price) %></span>
        </h2>

        

        <% if @deal.sellable? %>
          <p>Only <span class="lead text-primary"><%= @deal.quantity %></span> more left</p>
          <br>

          <div>
            <%= form_with(scope: :line_item, url: line_items_url(deal_id: @deal), local: true) do |form| %>
            
            <div class="form-group">
              <%= form.label :quantity%>
              <%= form.number_field :quantity, min: 1, max: @deal.quantity, value: 1, class: 'form-control' %>
            </div>

            <%= form.submit I18n.t(:add_to_cart, scope: :action), class: "btn btn-success btn-lg add-to-cart-btn" %>
            <% end %>
            <p><small class="form-text text-muted">Can be ordered only once.</small></p>
          </div>


        <% else %>
          <br>
          <p class="lead text-danger">Sold Out</p>
        <% end %>    
      </div>
   
      <hr class="col-md-11 col-xs-11">
      <div class="deal-description col-md-12 col-xs-12">
        <%= @deal.description.html_safe %>
      </div>
    
    </section>
  <div>
</article>


<div class="modal", data-modal='deal-show'>
  <div class="modal-dialog">
    <div class="modal-content modal-content-style">
      <div class="modal-body">
      </div>

      <div class="modal-footer">
        <%= link_to 'Reload', deal_path(@deal), class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
  </div>
</div>