config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  
  resources :registrations, only: [:new, :create, :edit, :update]

  resources :confirmations, only: [:new, :create]
  get 'user/confirm', to: 'confirmations#confirm'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :passwords, only: [:new, :create]
  get 'password/reset', to: 'passwords#edit'
  patch 'password/reset', to: 'passwords#update'

  get 'admin', to: redirect('admin/deals')

  namespace :admin do
    resources :deals
    resources :users, except: [:destroy]
    resources :orders, only: [:index, :show], param: :invoice_number do
      member do
        patch 'cancel'
        patch 'deliver'
      end
    end

    namespace :report do
      resources :deals_report, only: [:index]
      resources :customers_report, only: [:index]
      resources :revenue_report, only: [:index]
    end
  end

  resources :deals, only: [:index, :show] do
    member do
      get 'polling'
    end
  end

  resources :line_items, only: [:create, :destroy, :update]

  resources :orders, only: [:index, :destroy, :show], param: :invoice_number do
    patch 'cancel', on: :member
  end
  get 'cart', to: 'orders#cart'

  resources :addresses, only: [:new, :create]
  patch 'address/associate_address', to: "addresses#associate_address"

  resources :payments, only: [:new, :create]

  namespace :api do
    namespace :v1 do
      resources :deals, only: [] do
        collection do
          get 'live'
          get 'expired'
        end
      end

      resources :orders, path: :myorders, only: [:index]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Authenticable
  include TokenGenerator

  include Presentable

  attr_accessor :current_password

  has_secure_password
  has_secure_token :api_token
  has_secure_token :remember_me_token

  ## ASSOCATIONS
  has_many :orders, dependent: :restrict_with_error
  has_many :line_items, through: :orders
  has_many :payments, through: :orders
  has_many :addresses, dependent: :nullify

  ## VALIDATIONS
  with_options presence: true do
    validates :name
    validates :email, uniqueness: { case_sensitive: false }, format:{
      with: Regexp.new(ENV['email_regex']),
      allow_blank: true
    }

    validates :password, on: :update, if: :password_confirmation_present?
  end
  
  validates :password, allow_blank: true, length: { minimum: 6 }

  ## CALLBACKS
  before_update :clear_confirmed_token_sent_at, if: :confirmation_token_changed?
  before_update :clear_password_reset_token_sent_at, if: :password_reset_token_changed?
  after_commit :send_confirmation_instructions, on: :create


    def send_confirmation_instructions
      generate_confirmation_token
      UserMailer.confirmation_email(id, password).deliver_later
    end

    def send_password_reset_instructions
      generate_password_reset_token
      UserMailer.password_reset_email(id).deliver_later
    end

    def generate_password_reset_token
      update_columns(password_reset_token: generate_unique_token(:password_reset_token), password_reset_token_sent_at: Time.current)
    end

    def generate_confirmation_token
      update_columns(confirmation_token: generate_unique_token(:confirmation_token), confirmation_token_sent_at: Time.current)
    end

    def confirmation_token_expired?
      if confirmation_token_sent_at.nil? || confirmation_token.nil?
        return true
      end
      Time.current - confirmation_token_sent_at > CONFIRMATION_TOKEN_VALIDITY
    end

    def password_reset_token_expired?
      if password_reset_token_sent_at.nil? || password_reset_token.nil?
        return true
      end
      Time.current - password_reset_token_sent_at > PASSWORD_RESET_TOKEN_VALIDITY
    end

    def confirm
      update(confirmation_token: nil, confirmed_at: Time.current)
    end

    def recently_used_address_id
      # orders.last is not used because it will return the current_order user is working on
      if orders.complete.present?
        recently_used_address_id = orders.complete.last.address_id
      else
        recently_used_address_id = addresses.last.try(:id)
      end
      recently_used_address_id
    end

    def money_spend
      orders.where(state: ['completed', 'delivered']).sum(:total_amount)
    end

  private

    def clear_confirmed_token_sent_at
      self.confirmation_token_sent_at = nil if confirmation_token.nil?
    end

    def clear_password_reset_token_sent_at
      self.password_reset_token_sent_at = nil if password_reset_token.nil?
    end
    
    def password_confirmation_present?
      password_confirmation.present?
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_action :set_user, only: [:show, :edit, :update]
  before_action :ensure_not_admin, only: [:edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(new_user_params)
    if @user.save
      redirect_to admin_users_url, notice: t(:confirmation_email_sent, scope: [:flash, :notice])
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(update_user_params)
      redirect_to admin_users_url, notice: t(:customer_account_updated, scope: [:flash, :notice])
    else
      render :edit
    end
  end


  private

    def set_user
      @user = User.find_by(id: params[:id])
      unless @user.present?
        render_404
      end
    end

    def new_user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :active)
    end

    def update_user_params
      params.require(:user).permit(:name, :active, :password, :password_confirmation)
    end

    def ensure_not_admin
      if @user.admin?
        redirect_to admin_users_url, alert: t(:not_authorized, scope: [:flash, :alert])
      end
    end
end 

app/views/admin/users/_form.html.erb
<div class="form-group <%= 'has-error' if has_error?(:name, user) %>">
  <%= form.label :name, 'Name', class: 'required-field' %>
  <%= form.text_field :name, id: :user_name, class: 'form-control', placeholder: 'John Targaryn' %>
  <%= display_error(:name, user) %>
</div>

<div class="form-group <%= 'has-error' if has_error?(:email, user) %>">
  <%= form.label :email, 'Email Address', class: 'required-field' %>
  <%= form.email_field :email, id: :user_email, class: 'form-control', placeholder: 'myemail@gmail.com', disabled: email_disable_status %>
  <%= display_error(:email, user) %>
</div>

<div class="form-group">
  <%= form.label :active, 'Active:' %> &nbsp
  <%= form.check_box :active %>
</div>

 <div class="form-group <%= 'has-error' if has_error?(:password, @user) %>">
  <%= form.label :password, class: (@user.new_record? ? 'required-field' : '')  %>
  
  <%= form.password_field :password, id: :user_password, class: 'form-control', placeholder: '******' %>
  <% if @user.persisted? %>
    <small class="form-text text-muted">Leave this field blank if you don't want to update password</small>
  <% end %>
  <%= display_error(:password, @user) %>
</div>

<div class="form-group <%= 'has-error' if has_error?(:password_confirmation, @user) %>">
  <%= form.label :password_confirmation, 'Confirm Password', class: (@user.new_record? ? 'required-field' : '') %>
  <%= form.password_field :password_confirmation, id: :user_password_confirmation, class: 'form-control', placeholder: '******' %>
  <% if user.persisted? %>
    <small class="form-text text-muted">Leave this field blank if you don't want to update password</small>
  <% end %>
  <%= display_error(:password_confirmation, @user) %>
</div>

app/views/admin/users/edit.html.erb
<% content_for :page_title do %>
  <span class='page-title col-md-offset-10 col-xs-offset-10'>
    <%= link_to t(:user_page_title, scope: :action), admin_users_url %> /
    <%= @user.name %>
  </span>
<% end %>

<% content_for :page_action do %>
  <%= link_to t(:page_action_show, scope: [:action]), admin_user_url(@user), class: 'btn btn-info page-action col-md-offset-10 col-xs-offset-10' %>
<% end %>

<div class="form-div col-md-6 col-md-offset-3 col-xs-8 col-xs-offset-2">

  <% if @user.errors.any? %>
    <%= render 'shared/form_errors', model_object: @user %>
  <% end %>

  <%= form_with(scope: @user, url: admin_user_path(@user), local: true, method: :patch) do |form| %>
    <fieldset>
      <div class="form-group">
        <h4 class= 'col-md-offset-5 col-xs-offset-5'>Update User</h4>
      </div>

      <%= render 'form', form: form, user: @user, email_disable_status: true %>

      <%= form.submit t(:update_profile, scope: [:action]), class: 'btn btn-primary col-md-offset-5' %>
    </fieldset>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<% content_for :page_action do %>
  <%= link_to t(:page_action_new_user, scope: [:action]), new_admin_user_url, class: 'btn btn-success col-md-offset-10 col-xs-offset-9 page-action' %>
<% end %>

<% content_for :page_title do %>
  <span class="col-md-offset-10 col-xs-offset-10 page-title"><%= t(:user_page_title, scope: [:action]) %></span>
<% end %>


<div class="table-responsive">
  <div class="panel panel-default">  
    <table class="table table-striped table-hover ">

      <thead>
        <tr>
          <th nowrap>#</th>
          <th nowrap>NAME</th>
          <th nowrap>EMAIL</th>
          <th nowrap>ADMIN</th>
          <th nowrap>CONFIRMED AT</th>
          <th nowrap>STATUS</th>
        </tr>
      </thead>
      
      <tbody>
        <% @users.each.with_index(1) do |user, serial_number| %>
          <tr>

            <td><%= serial_number %></td>

            <td><%= user.name %></td>

            <td><%= user.email%></td>

            <td><%= user.admin? %></td>

            <td><%= user.presenter.confirmation_status %></td>

            <td><%= user.presenter.status %></td>
            <td>
              <%= link_to t(:page_action_show, scope: [:action]), admin_user_url(user) %>
              <% unless user.admin? %>
                | <%= link_to t(:page_action_edit, scope: [:action]), edit_admin_user_url(user)%>
              <% end %>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<% content_for :page_title do %>
  <div class='col-md-offset-5 col-xs-offset-5 page-title'>
    <%= link_to t(:user_page_title, scope: :action), admin_users_url%> / 
    <%= t(:new, scope: [:action]) %>
  </div>
<% end %>

<div class="form-div col-md-6 col-md-offset-3 col-xs-8 col-xs-offset-2">

  <% if @user.errors.any? %>
    <%= render 'shared/form_errors', model_object: @user %>
  <% end %>

  <%= form_with(scope: @user, url: admin_users_path, local: true) do |form| %>
    <fieldset>
      <div class="form-group">
        <h4 class= 'col-md-offset-4'>Create User</h4>
      </div>

      <%= render 'form', form: form, user: @user, email_disable_status: false %>
      
      <%= form.submit t(:create_customer, scope: [:action]), class: 'btn btn-primary col-md-offset-5' %>
     </fieldset>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<% content_for :page_title do %>
  <span class="page-title <%= @user.admin?? 'col-md-offset-5  col-xs-offset-5' : 'col-md-offset-10  col-xs-offset-10' %>">
    <%= link_to t(:user_page_title, scope: [:action]), admin_users_url %> /
    <%= @user.name %>
  </span>
<% end %>

<% unless @user.admin? %>
  <% content_for :page_action do %>
    <%= link_to t(:page_action_edit, scope: [:action]), edit_admin_user_url(@user), class: 'btn btn-success page-action col-md-offset-10 col-xs-offset-10' %>
  <% end %>
<% end %>

<div class="row panel">
  <div class="col-md-8 col-xs-8 col-md-offset-2 col-xs-offset-2">
    <div class="panel panel-default">
      <table class='table table-striped table-hover'>
        <tr>
          <td>Name</td>
          <td><%= @user.name %></td>
        </tr>
        
        <tr>
          <td>Email Id</td>
          <td><%= @user.email %></td>
        </tr>

        <tr>
          <td>Status</td>
          <td>
            <%= @user.presenter.status %>
          </td>
        </tr>
        
        <tr>
          <td>Admin</td>
          <td><%= @user.admin? %></td>
        </tr>
        
        <tr>
          <td>Confirmed at</td>
          <td><%= @user.presenter.confirmation_status %></td>
        </tr>

      </table>
    </div>
  </div>
</div>